import subprocess
import sys
from pathlib import Path

from http_host_lib.config import config
from http_host_lib.utils import python_venv_executable


def get_tile_auth_secrets() -> dict:
    """Return the configured tile-server auth secrets as a {kid: secret} dict.

    Source is the optional ``tile_auth_secrets`` object in ``config.json`` (e.g.
    ``{"k1": "secretA", "k2": "secretB"}``). When it is absent or empty, tile-server
    authentication is disabled: no ``$ofm_secret`` map is written, no ``secure_link``
    directives are emitted and no location carries the ``secure_link`` guard, so every
    request is served exactly as before. Keeping several ids configured at once enables
    zero-downtime secret rotation (old ids stay valid until their tokens have expired).
    """
    raw = config.ofm_config.get('tile_auth_secrets') or {}
    return {str(kid): str(secret) for kid, secret in raw.items()}


def secure_link_guard() -> str:
    """Return the per-location ``secure_link`` guard, or '' when auth is disabled.

    Inserted (via the ``__SECURE_LINK_GUARD__`` placeholder) right after each protected
    location's OPTIONS/preflight block, so CORS preflights still short-circuit with 204
    before any token is required. ``$secure_link`` is nginx's built-in verdict: ``''`` for
    a missing/malformed token, ``'0'`` for a bad or expired one and ``'1'`` for a valid,
    unexpired one; both ``''`` and ``'0'`` are rejected. The 401 carries
    ``Access-Control-Allow-Origin`` because the app runs on a different ``*.sapsailing.com``
    host than the tile server, so without it the cross-origin browser would see an opaque
    error instead of a 401 and could not refresh the token.
    """
    if not get_tile_auth_secrets():
        return ''
    return (
        "\n"
        "        # tile-server access token (secure_link) required; secret via $ofm_secret map\n"
        "        if ($secure_link = '') {\n"
        "            add_header 'Access-Control-Allow-Origin' '*' always;\n"
        "            return 401;\n"
        "        }\n"
        "        if ($secure_link = '0') {\n"
        "            add_header 'Access-Control-Allow-Origin' '*' always;\n"
        "            return 401;\n"
        "        }\n"
    )


def secure_link_server_directives() -> str:
    """Return the server-level ``secure_link`` directives, or '' when auth is disabled.

    Inserted via the ``__SECURE_LINK_SERVER__`` placeholder in ``direct.conf``.
    ``secure_link`` reads the signature and expiry from the ``X-OFM-Md5`` / ``X-OFM-Expires``
    request headers (so tile URLs stay cacheable), and ``secure_link_md5`` recomputes
    ``md5("<expires> <secret>")`` with the secret selected by the http-level ``$ofm_secret``
    map keyed on the ``X-OFM-Kid`` header.
    """
    if not get_tile_auth_secrets():
        return ''
    return (
        "    # short-lived tile-server access tokens; secret selected by the $ofm_secret map\n"
        "    # in /data/nginx/config/ofm_secure_link.conf; token travels in request headers\n"
        "    secure_link $http_x_ofm_md5,$http_x_ofm_expires;\n"
        "    secure_link_md5 \"$secure_link_expires $ofm_secret\";\n"
    )


def write_secure_link_map():
    """(Re)write the http-level ``$ofm_secret`` map used by ``secure_link_md5``.

    Written to ``/data/nginx/config/ofm_secure_link.conf``, which ``nginx.conf`` includes
    at http level *before* the server blocks in ``sites/``. The map turns the client-sent
    ``X-OFM-Kid`` header into the matching signing secret; an unknown or absent kid maps to
    the empty default secret, which makes ``$secure_link`` evaluate to ``''``/``'0'`` so the
    guard rejects the request. When no secrets are configured the file is removed, disabling
    tile-server auth entirely.
    """
    map_path = Path('/data/nginx/config/ofm_secure_link.conf')
    secrets = get_tile_auth_secrets()
    if not secrets:
        map_path.unlink(missing_ok=True)
        return
    lines = [
        '# Auto-generated by http_host_lib/nginx.py - do not edit by hand.',
        '# Selects the tile-server signing secret from the client-sent X-OFM-Kid header so',
        '# secure_link_md5 can validate the token. Unknown/absent kid -> empty secret ->',
        '# $secure_link is ""/"0" -> the per-location guard returns 401.',
        'map $http_x_ofm_kid $ofm_secret {',
        '    default "";',
    ]
    for kid, secret in secrets.items():
        lines.append(f'    "{kid}" "{secret}";')
    lines.append('}')
    map_path.parent.mkdir(parents=True, exist_ok=True)
    map_path.write_text('\n'.join(lines) + '\n')


def write_nginx_config():
    print('Writing nginx config')

    if not config.mnt_dir.exists():
        sys.exit('  mount needs to be run first')

    domain_direct = config.ofm_config['domain_direct']

    # (Re)write the http-level kid->secret map before validating/reloading nginx, so the
    # $ofm_secret variable referenced by the server-level secure_link_md5 directive exists.
    write_secure_link_map()

    # remove old configs
    for file in Path('/data/nginx/sites').glob('ofm_*.conf'):
        file.unlink()

    # TLS is terminated upstream (e.g. an AWS ALB); nginx serves plain HTTP on
    # port 80 only, so there are no certificates to install or link here.
    curl_text_mix = create_nginx_conf(
        template_path=config.nginx_confs / 'direct.conf',
        local='ofm_direct',
        domain=domain_direct,
    )

    subprocess.run(['nginx', '-t'], check=True)
    subprocess.run(['systemctl', 'reload', 'nginx'], check=True)

    curl_text_lines = sorted(curl_text_mix.splitlines())
    if config.ofm_config.get('skip_planet'):
        curl_text_lines = [l for l in curl_text_lines if '/planet' not in l]
    else:
        curl_text_lines = [l for l in curl_text_lines if '/monaco' not in l]

    curl_text_mix = '\n'.join(curl_text_lines)
    print(f'test with:\n{curl_text_mix}')


def create_nginx_conf(*, template_path, local, domain):
    location_str, curl_text = create_location_blocks(local=local, domain=domain)

    with open(template_path) as fp:
        template = fp.read()

    template = template.replace('__LOCATION_BLOCKS__', location_str)
    template = template.replace('__LOCAL__', local)
    template = template.replace('__DOMAIN__', domain)
    # Fill the secure_link placeholders last so they also reach the location blocks (both the
    # generated ones and the appended location_static.conf); empty strings when auth is disabled.
    template = template.replace('__SECURE_LINK_SERVER__', secure_link_server_directives())
    template = template.replace('__SECURE_LINK_GUARD__', secure_link_guard())

    curl_text = curl_text.replace('__LOCAL__', local)
    curl_text = curl_text.replace('__DOMAIN__', domain)

    with open(f'/data/nginx/sites/{local}.conf', 'w') as fp:
        fp.write(template)
        print(f'  nginx config written: {domain} {local}')

    return curl_text


def create_location_blocks(*, local, domain):
    location_str = ''
    curl_text = ''

    for subdir in config.mnt_dir.iterdir():
        if not subdir.is_dir():
            continue
        area, version = subdir.name.split('-')

        location_str += create_version_location(
            area=area, version=version, mnt_dir=subdir, local=local, domain=domain
        )

        for path in [
            f'/{area}/{version}',
            f'/{area}/{version}/14/8529/5975.pbf',
            f'/{area}/{version}/9999/9999/9999.pbf',  # empty_tile test
        ]:
            curl_text += (
                # f'curl -H "Host: __LOCAL__" -I http://localhost/{path}\n'
                f'curl -sI https://__DOMAIN__{path} | sort\n'
            )

    location_str += create_latest_locations(local=local, domain=domain)

    for area in config.areas:
        for path in [
            f'/{area}',
            f'/{area}/19700101_old_version_test',
            f'/{area}/19700101_old_version_test/14/8529/5975.pbf',
            f'/{area}/19700101_old_version_test/9999/9999/9999.pbf',  # empty_tile test
        ]:
            curl_text += (
                # f'curl -H "Host: __LOCAL__" -I http://localhost/{path}\n'
                f'curl -sI https://__DOMAIN__{path} | sort\n'
            )

    with open(config.nginx_confs / 'location_static.conf') as fp:
        location_str += '\n' + fp.read()

    return location_str, curl_text


def create_version_location(
    *, area: str, version: str, mnt_dir: Path, local: str, domain: str
) -> str:
    run_dir = config.runs_dir / area / version
    if not run_dir.is_dir():
        print(f"  {run_dir} doesn't exist, skipping")
        return ''

    tilejson_path = run_dir / f'tilejson-{local}.json'

    metadata_path = mnt_dir / 'metadata.json'
    if not metadata_path.is_file():
        print(f"  {metadata_path} doesn't exist, skipping")
        return ''

    url_prefix = f'https://{domain}/{area}/{version}'

    subprocess.run(
        [
            python_venv_executable(),
            config.http_host_scripts_dir / 'metadata_to_tilejson.py',
            '--minify',
            metadata_path,
            tilejson_path,
            url_prefix,
        ],
        check=True,
    )

    return f"""
    # specific JSON {area} {version}
    location = /{area}/{version} {{ # no trailing slash
        alias {tilejson_path}; # no trailing slash

        if ($request_method = 'OPTIONS') {{
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Max-Age' 86400 always;
            return 204;
        }}
__SECURE_LINK_GUARD__
        expires 1w;
        default_type application/json;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header Cache-Control public;
        add_header X-Robots-Tag "noindex, nofollow" always;

        add_header x-ofm-debug 'specific JSON {area} {version}';
    }}

    # specific PBF {area} {version}
    location ^~ /{area}/{version}/ {{ # trailing slash
        alias {mnt_dir}/tiles/; # trailing slash

        if ($request_method = 'OPTIONS') {{
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Max-Age' 86400 always;
            return 204;
        }}
__SECURE_LINK_GUARD__
        try_files $uri @empty_tile;
        add_header Content-Encoding gzip;

        expires 10y;

        types {{
            application/vnd.mapbox-vector-tile pbf;
        }}

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header Cache-Control public;
        add_header X-Robots-Tag "noindex, nofollow" always;

        add_header x-ofm-debug 'specific PBF {area} {version}';
    }}
    """


def create_latest_locations(*, local: str, domain: str) -> str:
    location_str = ''

    local_version_files = config.deployed_versions_dir.glob('*.txt')

    for file in local_version_files:
        area = file.stem
        with open(file) as fp:
            version = fp.read().strip()

        print(f'  linking latest version for {area}: {version}')

        # checking runs dir
        run_dir = config.runs_dir / area / version
        tilejson_path = run_dir / f'tilejson-{local}.json'
        if not tilejson_path.is_file():
            print(f'    error with latest: {tilejson_path} does not exist')
            continue

        # checking mnt dir
        mnt_dir = Path(f'/mnt/ofm/{area}-{version}')
        mnt_file = mnt_dir / 'metadata.json'
        if not mnt_file.is_file():
            print(f'    error with latest: {mnt_file} does not exist')
            continue

        # latest
        location_str += f"""

        # latest JSON {area}
        location = /{area} {{ # no trailing slash
            alias {tilejson_path}; # no trailing slash

            if ($request_method = 'OPTIONS') {{
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' '*' always;
                add_header 'Access-Control-Max-Age' 86400 always;
                return 204;
            }}
__SECURE_LINK_GUARD__
            expires 1d;
            default_type application/json;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header Cache-Control public;
            add_header X-Robots-Tag "noindex, nofollow" always;

            add_header x-ofm-debug 'latest JSON {area}';
        }}
        """

        # wildcard
        # identical to create_version_location
        location_str += f"""

        # wildcard JSON {area}
        location ~ ^/{area}/([^/]+)$ {{
            # regex location is unreliable with alias, only root is reliable

            root {run_dir}; # no trailing slash

            if ($request_method = 'OPTIONS') {{
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' '*' always;
                add_header 'Access-Control-Max-Age' 86400 always;
                return 204;
            }}
__SECURE_LINK_GUARD__
            try_files /tilejson-{local}.json =404;

            expires 1w;
            default_type application/json;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header Cache-Control public;
            add_header X-Robots-Tag "noindex, nofollow" always;

            add_header x-ofm-debug 'wildcard JSON {area}';
        }}

        # wildcard PBF {area}
        location ~ ^/{area}/([^/]+)/(.+)$ {{
            # regex location is unreliable with alias, only root is reliable

            root {mnt_dir}/tiles/; # trailing slash

            if ($request_method = 'OPTIONS') {{
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' '*' always;
                add_header 'Access-Control-Max-Age' 86400 always;
                return 204;
            }}
__SECURE_LINK_GUARD__
            try_files /$2 @empty_tile;
            add_header Content-Encoding gzip;

            expires 10y;

            types {{
                application/vnd.mapbox-vector-tile pbf;
            }}

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header Cache-Control public;
            add_header X-Robots-Tag "noindex, nofollow" always;

            add_header x-ofm-debug 'wildcard PBF {area}';
        }}
        """

        # health probe {area}
        # A GET to /healthz/{area} returns 204 (empty body) iff the btrfs image
        # for this run is mounted, and 503 otherwise. The discriminator is the
        # tiles/ directory: the mountpoint dir /mnt/ofm/{area}-{version} always
        # exists, but tiles/ only appears when the image is mounted. The -d test
        # stat()s the dir (no read, empty body either way); this leaves the real
        # /tiles/ tile-serving path untouched, and gives the ALB a truthful
        # signal instead of the masked 200 that @empty_tile returns for real
        # tile requests once a mount drops. `if` here only guards a `return`,
        # which is a sanctioned use of if in a location context.
        location_str += f"""

        # health probe {area}
        location = /healthz/{area} {{
            access_log off;
            if (!-d {mnt_dir}/tiles) {{
                return 503;
            }}
            add_header x-ofm-debug 'healthz {area}' always;
            return 204;
        }}
        """

    return location_str

